language: node_js
node_js:
  - "10"
git:
  quite: true
  depth: 1
  submodules: false
cache: 
  directories: node_modules
before_script: export NODE_OPTIONS=–max_old_space_size=4096
script: npm run-script build
