language: node_js
node_js:
    - '10'
install:
    - npm install
sudo: required
git:
   - depth: 1
branches:
   only:
    - master
script:
    - unset CI
    - npm run build
    - npm run test -- --watchAll=false --runInBand
